apiVersion: v1
kind: Pod
metadata:
  name: tectonic-node-controller
  namespace: kube-system
  labels:
    k8s-app: tectonic-node-controller
spec:
  containers:
  - name: tectonic-node-controller
    image: ${tnc_bootstrap_image}
    args:
    - --config=/etc/cluster-config/tnc-config
    - --port=49500
    - --debug
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 50Mi
    volumeMounts:
    - name: cluster-config
      mountPath: /etc/cluster-config/tnc-config
  hostNetwork: true
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  volumes:
  - name: cluster-config
    hostPath:
      path: /opt/tectonic/tnc-config
