#cloud-config

hostname: ${node_name}

coreos:
  update:
    reboot-strategy: "etcd-lock"
  etcd2:
    name: ${node_name}
    discovery-srv: ${etcd_domain}
    listen-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379"
    initial-advertise-peer-urls: "http://${node_name}:2380"
    advertise-client-urls: "http://${node_name}:2379"
  units:
    - name: "etcd.service"
      enable: false
    - name: "etcd2.service"
      enable: false
      command: start
